### PR TITLE
Add [default_]track_scorer_name entries, goes with CMSSW #40490.

### PR DESCRIPTION
**Pull request by osschar**

### CODE REVIEW

**Comment by osschar** [comment]
These changes are required by cms-sw/cmssw#40490

**Comment by perrotta** [comment]
+1
- Needed by https://github.com/cms-sw/cmssw/pull/40490

**Comment by perrotta** [comment]
merge
- (The corresponding CMSSW PR was already signed by reco)

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
