### PR TITLE
Update of mkFit JSON configurations following PR cms-sw/cmssw#37580

### PR DESCRIPTION
**Pull request by mmasciov**
As per title, this PR updates mkFit JSON configurations following PR cms-sw/cmssw#37580.

### CODE REVIEW

**Comment by jpata** [comment]
+reconstruction
- tested in https://github.com/cms-sw/cmssw/pull/37580#issuecomment-1100374477

**Comment by perrotta** [comment]
+1
- It was already tested together with #37580, and it must be merged with it

**Comment by smuzaffar** [comment]
+externals

**Comment by perrotta** [comment]
merge
- (also #37580 is merged)

**Pull request merged**
