### PR TITLE
Update mkFit JSON files for 12_1_0_pre4

### PR DESCRIPTION
**Pull request by mmasciov**
Update of per-iteration JSON files for mkFit configuration, as per PR cms-sw/cmsdist#7349 and cms-sw/cmssw#35492

### CODE REVIEW

**Comment by jpata** [comment]
+reconstruction
- tested at https://github.com/cms-sw/cmssw/pull/35492#issuecomment-933869632
- required for https://github.com/cms-sw/cmssw/pull/35492

**Comment by jpata** [comment]
test parameters:
  - pull_requests = https://github.com/cms-sw/cmsdist/pull/7349, https://github.com/cms-sw/cmssw/pull/35492

**Comment by jpata** [comment]
The test actually passed in the CMSSW PR.

**Comment by perrotta** [comment]
+1
- To be merged together with #35492

**Comment by perrotta** [comment]
@smuzaffar let me merge this, together with #35492, as decided right now in the ORP: please let me know if there are issues that I overlooked

**Comment by perrotta** [comment]
merge

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@perrotta thanks for merging it. Once data pr is merged then cmsdist PR is automatically open. In this case cmsdist PR is  cms-sw/cmsdist#7361 . So  cms-sw/cmsdist#7361 should also be merged in order to get these new data files. I am merging  cms-sw/cmsdist#7361 now

**Comment by perrotta** [comment]
Thank you @smuzaffar !

**Pull request merged**
