### PR TITLE
Update per-iteration JSON files for mkFit configuration (121X)

### PR DESCRIPTION
**Pull request by mmasciov**
Update of per-iteration JSON files for mkFit configuration, as per PR cms-sw/cmsdist#7217 and cms-sw/cmssw#34921

### CODE REVIEW

**Comment by jpata** [comment]
+reconstruction
- tested in https://github.com/cms-sw/cmssw/pull/34921#issuecomment-901485763

**Comment by mrodozov** [comment]
+externals

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
@jpata this is good to get in regardless of the cmssw PR ?

**Comment by jpata** [comment]
I believe this should be merged just before the corresponding CMSSW PR. For the moment we can wait until that one is signed.

**Comment by jpata** [comment]
@mrodozov from the reco point of view, this could be merged now, concurrently with https://github.com/cms-sw/cmssw/pull/34921 (once it's fully signed).

**Comment by mrodozov** [comment]
I was asking if this is final so we can tag it and prepare the cmsdist change

**Comment by mmasciov** [comment]
> I was asking if this is final so we can tag it and prepare the cmsdist change

Just to confirm that no further change is expected before the next pre-release.
All changes for the next pre-release are in this PR, together with cms-sw/cmsdist#7229 and cms-sw/cmssw#34921

**Pull request merged**
