### PR TITLE
Add values for new member bool IterationParams::recheckOverlap.

### PR DESCRIPTION
**Pull request by osschar**
These JSON changes go along with trackreco/cmssw#118

### CODE REVIEW

**Comment by slava77** [comment]
> These JSON changes go along with [trackreco/cmssw#118](https://github.com/trackreco/cmssw/pull/118)

@osschar 
this PR is in a general cms-data repo; was it intended to be made here or in the trackreco as well?

**Comment by osschar** [comment]
Oh, yes, I wanted it to go to trackreco, sorry about that.
Presumably this will become useful here as well -- so let's just put it on hold for now.
I created a separate trackreco one, trackreco/RecoTracker-MkFit#2

**Comment by slava77** [comment]
@rappoccio 
this is required with cms-sw/cmssw#43580  (which was merged)

**Comment by smuzaffar** [comment]
+externals

This has been tested via https://github.com/cms-sw/cmssw/pull/43580

**Comment by smuzaffar** [comment]
@rappoccio , as https://github.com/cms-sw/cmssw/pull/43580 has been merged so I am merging this one too otherwise we might have broken IBs

**Pull request merged**
