### PR TITLE
Update mkFit JSON files for CMSSW_12_1_0_pre5

### PR DESCRIPTION
**Pull request by mmasciov**
Update of per-iteration JSON files for mkFit configuration, as per PR cms-sw/cmsdist#7387 and cms-sw/cmssw#35652

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#35652,cms-sw/cmsdist#7387

**Comment by jpata** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1
- To be merged together with #35652

**Comment by perrotta** [comment]
merge

**Pull request merged**
