### PR TITLE
Update JSON files in line with changes done in cms-sw/cmssw#39866

### PR DESCRIPTION
**Pull request by osschar**
Update JSON files in line with changes introduced in cms-sw/cmssw#39866

In particular:
- introduce standard function names so they can be set-up through JSON or CMSSW config;
- consolidate seed-cleaning and duplicate-cleaning parameters names and move them into the top-level IterationConfig struct (moved out of IterationParams, a sub-structure that exists in two instances, for forward search and for backward fit / search).

### CODE REVIEW

**Comment by mandrenguyen** [comment]
+reconstruction
tested in #39866

**Comment by slava77** [comment]
> -1
> 
> **Failed Tests**:

@smuzaffar 
is there a way for auto-submitted tests to figure out that they were already done in connection with another PR?

It seems like we are regularly getting failures on tests of externals that require a cms-sw/cmssw PR. The coupled tests done in cms-sw/cmssw PR plus the external pass OK, but the post-signoff auto-tests make an impression of broken PR (and also burn some unnecessary CPU).

**Comment by smuzaffar** [comment]
> > -1
> > **Failed Tests**:
> 
> @smuzaffar is there a way for auto-submitted tests to figure out that they were already done in connection with another PR?
> 
> It seems like we are regularly getting failures on tests of externals that require a cms-sw/cmssw PR. The coupled tests done in cms-sw/cmssw PR plus the external pass OK, but the post-signoff auto-tests make an impression of broken PR (and also burn some unnecessary CPU).

@slava77 , no currently there is no way to do that. We can disable auto-start of tests for data PRs on signature ( means for data PRs requires an explicit `please test` )

**Comment by slava77** [comment]
> @slava77 , no currently there is no way to do that. We can disable auto-start of tests for data PRs on signature ( means for data PRs requires an explicit `please test` )

that could be an improvement
will it be a part of `test parameters` or a hardcoded default?

**Comment by smuzaffar** [comment]
> > @slava77 , no currently there is no way to do that. We can disable auto-start of tests for data PRs on signature ( means for data PRs requires an explicit `please test` )
> 
> that could be an improvement will it be a part of `test parameters` or a hardcoded default?

hard-coded default applied only to cms-data repositories

**Comment by mmusich** [comment]
I guess this PR needs to be merged now after https://github.com/cms-sw/cmssw/pull/39866 is merged.
There are massive relval failures in the [last IB](https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_12_6/2022-11-21-2300?selectedArchs=el9_aarch64_gcc11&selectedFlavors=X&selectedStatus=failed)

**Comment by perrotta** [comment]
+1
- It must go (and it was tested together) https://github.com/cms-sw/cmssw/pull/39866

**Comment by perrotta** [comment]
merge

**Comment by smuzaffar** [comment]
> > @slava77 , no currently there is no way to do that. We can disable auto-start of tests for data PRs on signature ( means for data PRs requires an explicit `please test` )
> 
> that could be an improvement will it be a part of `test parameters` or a hardcoded default?

@slava77 , bot now does not start tests on signatures for non-cmssw repositories. One need to explicitly request the start of tests by `please test` comment. Bot behavior is not changed for cmssw repo and it will trigger the tests on first signature

**Comment by slava77** [comment]
> @slava77 , bot now does not start tests on signatures for non-cmssw repositories. One need to explicitly request the start of tests by `please test` comment. Bot behavior is not changed for cmssw repo and it will trigger the tests on first signature

Thank you.
Noted.

Taking this PR as an example, it may also help to figure out how to synchronously merge.
E.g. (less automation) if a PR is declared as a dependency the last "+1" from the ORP wouldn't yet merge and there would be a message reminding of the dependency.

**Pull request merged**
